UA/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'UA'

urlpatterns = [
    path('', views.index, name='UA_index'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.login_page, name='ua_login'),
    path('user-login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
]

UserAuthentication/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UA.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UA/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    facebook_link = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True) 

    def __str__(self):
        return self.user.username

UA/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from . import models


class UserForm(ModelForm):
    password = forms.CharField(
        max_length=6,
        widget=forms.PasswordInput(),
    )
    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UserInfoForm(ModelForm):
    class Meta:
        model = models.UserInfo
        fields = ['facebook_link', 'profile_pic']

UA/views.py
from django.shortcuts import render
from . import forms
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from . import models
from django.conf import settings
from django.contrib.auth.decorators import user_passes_test



#Logout required decorators 
def logout_required(function=None, logout_url=None):
    """
    Decorator for views that checks that the user is logged out, redirecting
    to the home page if necessary.
    """
    actual_decorator = user_passes_test(
        lambda u: not u.is_authenticated,
        login_url=logout_url,
    )
    if function:
        return actual_decorator(function)
    return actual_decorator

# Create your views here.

@login_required(login_url='/login/')
def index(request):
    user_id = request.user.id
    basics  = User.objects.get(pk=user_id)
    others = models.UserInfo.objects.get(user=user_id)
    dictionary = {
        'basics': basics,
        'others': others,
    }
    return render(request, 'ua/index.html', context=dictionary)

@logout_required(logout_url='/')
def registration(request):
    userForm = forms.UserForm()
    userInfoForm = forms.UserInfoForm()
    registered = False
    
    if request.method == 'POST':
        userFormData = forms.UserForm(data=request.POST)
        userInfoFormData = forms.UserInfoForm(data=request.POST)

        if userFormData.is_valid() and userInfoFormData.is_valid():
            user = userFormData.save()
            user.set_password(user.password)
            user.save()

            user_info = userInfoFormData.save(commit=False)
            user_info.user = user

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']

            user_info.save()
            registered = True    
    # else:
    #     userForm = forms.UserForm()
    #     userInfoForm = forms.UserInfoForm()

    dictionary = {
        'userForm': userForm,
        'userInfoForm': userInfoForm,
        'registered': registered,
    }
    return render(request, 'ua/registration.html', context=dictionary)


def login_page(request):
    dictionary = {

    }   
    return render(request, 'ua/login.html', context=dictionary)   


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('UA:UA_index'))
            return HttpResponse('Your Account is Inactive!!')
        else:
            return HttpResponse("Invalid Credentials!!")        
    
    return HttpResponseRedirect(reverse('UA:ua_login'))


@login_required(login_url='/login/')
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('UA:ua_login'))

templates/ua/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <title>{{ title }}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'UA:UA_index' %}">
              Home <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'UA:logout' %}">
              Logout   
            </a>
          </li>  
          {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'UA:ua_login' %}">
              Login   
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'UA:registration' %}">
              Register   
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container" style="padding-top: 20px;">
      {% block body_block %}

      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </body>
</html>

templates/ua/index.html
{% extends 'ua/base.html' %}

{% block body_block %}
<p>Hi {{ basics.username }},</p>
<p>Your Email: {{ basics.email }}</p>
<p><a href="{{ others.facebook_link }}">Facebook Profile</a></p>
<p><img src="/media/{{ others.profile_pic }}" width="200px"></p>
{% endblock body_block %}

templates/ua/login.html
{% extends 'ua/base.html' %}


{% block body_block %}
<form action="{% url 'UA:user_login' %}" method="POST">
    {% csrf_token %}
    <h2 class="text-center">Log in</h2>       
    <div class="form-group">
        <input type="text" class="form-control" name="username" placeholder="Username" required="required">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="Password" required="required">
    </div>
    <div class="form-group">
        <input type="submit" name="submit" class="btn btn-primary btn-block" value="Log in">
    </div>       
</form>
{% endblock body_block %}
    

templates/ua/registration.html
{% extends 'ua/base.html' %}

{% load static %}

{% block body_block %}


{% if registered %}
    <div class="alert alert-success">
        Congratulations! Your Registration is Complete!!
    </div>
{% else %}
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ userForm.as_p }}
        {{ userInfoForm.as_p }}
        <input type="submit" name="submit" value="Register">
    </form>
{% endif %}
    
{% endblock body_block %}